In [184]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [185]:
df=pd.read_csv("Delhi_v2.csv")

df

,Unnamed: 0,price,Address,area,latitude,longitude,Bedrooms,Bathrooms,Balcony,Status,neworold,parking,Furnished_status,Lift,Landmarks,type_of_building,desc,Price_sqft
0,0,5600000.0,"Noida Extension, Noida, Delhi NCR",1350.0,28.608850,77.460560,3.0,3.0,NaN,Under Construction,New Property,NaN,NaN,2.0,NaN,Flat,\n\n\n Welcome ...,4148.148148
1,1,8800000.0,"Sector 79, Gurgaon, Delhi NCR",1490.0,28.374236,76.952416,3.0,3.0,NaN,Ready to Move,New Property,NaN,Semi-Furnished,2.0,NaN,Flat,\n\n\n Mapsko M...,5906.040268
2,2,16500000.0,"Vaishali, Ghaziabad, Delhi NCR",2385.0,28.645769,77.385110,4.0,5.0,NaN,Ready to Move,New Property,1.0,Unfurnished,NaN,NaN,Flat,\n\n\n This pro...,6918.238994
3,3,3810000.0,"Link Road, F Block, Sector 50, Noida, Uttar Pr...",1050.0,28.566914,77.436434,2.0,2.0,3.0,NaN,New Property,1.0,Unfurnished,2.0,near Gaur Mulberry Mansion,Flat,\n\n\n AIG Roya...,3628.571429
4,4,6200000.0,"Jaypee Pavilion Court Sector 128, Noida, Secto...",1350.0,28.520732,77.356491,2.0,2.0,3.0,Ready to Move,Resale,1.0,NaN,3.0,NaN,Flat,\n\n\n The prop...,4592.592593
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7733,7733,7900000.0,"Indirapuram, Ghaziabad, Delhi NCR",1095.0,28.635272,77.370395,2.0,2.0,NaN,Ready to Move,Resale,NaN,NaN,NaN,NaN,Flat,\n \n \n...,7214.611872
7734,7734,4510000.0,"Greater Noida, Sector 2, Greater Noida, Delhi NCR",1060.0,28.581431,77.452819,2.0,2.0,3.0,NaN,Resale,NaN,Semi-Furnished,NaN,ek murti chowk,Flat,\n \n \n...,4254.716981
7735,7735,7000000.0,"Crossings Republik, Ghaziabad, Delhi NCR",1898.0,28.625850,77.435336,4.0,3.0,5.0,Ready to Move,Resale,NaN,NaN,NaN,NaN,Flat,\n \n \n...,3688.092729
7736,7736,6500000.0,"Raj Nagar Extension, Ghaziabad, Raj Nagar Exte...",1400.0,28.701622,77.430153,3.0,3.0,2.0,Ready to Move,Resale,1.0,NaN,3.0,vvip mall,Flat,\n \n \n...,4642.857143
7737,7737,6500000.0,"sandal apartment, Shalimar Garden Extension 1,...",1750.0,28.693590,77.344376,3.0,2.0,3.0,Ready to Move,New Property,NaN,NaN,NaN,NaN,Flat,\n,3714.285714

In [186]:
df['price']=df['price']/100000
df['area']=df['area']/1000

df

,Unnamed: 0,price,Address,area,latitude,longitude,Bedrooms,Bathrooms,Balcony,Status,neworold,parking,Furnished_status,Lift,Landmarks,type_of_building,desc,Price_sqft
0,0,56.0,"Noida Extension, Noida, Delhi NCR",1.350,28.608850,77.460560,3.0,3.0,NaN,Under Construction,New Property,NaN,NaN,2.0,NaN,Flat,\n\n\n Welcome ...,4148.148148
1,1,88.0,"Sector 79, Gurgaon, Delhi NCR",1.490,28.374236,76.952416,3.0,3.0,NaN,Ready to Move,New Property,NaN,Semi-Furnished,2.0,NaN,Flat,\n\n\n Mapsko M...,5906.040268
2,2,165.0,"Vaishali, Ghaziabad, Delhi NCR",2.385,28.645769,77.385110,4.0,5.0,NaN,Ready to Move,New Property,1.0,Unfurnished,NaN,NaN,Flat,\n\n\n This pro...,6918.238994
3,3,38.1,"Link Road, F Block, Sector 50, Noida, Uttar Pr...",1.050,28.566914,77.436434,2.0,2.0,3.0,NaN,New Property,1.0,Unfurnished,2.0,near Gaur Mulberry Mansion,Flat,\n\n\n AIG Roya...,3628.571429
4,4,62.0,"Jaypee Pavilion Court Sector 128, Noida, Secto...",1.350,28.520732,77.356491,2.0,2.0,3.0,Ready to Move,Resale,1.0,NaN,3.0,NaN,Flat,\n\n\n The prop...,4592.592593
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7733,7733,79.0,"Indirapuram, Ghaziabad, Delhi NCR",1.095,28.635272,77.370395,2.0,2.0,NaN,Ready to Move,Resale,NaN,NaN,NaN,NaN,Flat,\n \n \n...,7214.611872
7734,7734,45.1,"Greater Noida, Sector 2, Greater Noida, Delhi NCR",1.060,28.581431,77.452819,2.0,2.0,3.0,NaN,Resale,NaN,Semi-Furnished,NaN,ek murti chowk,Flat,\n \n \n...,4254.716981
7735,7735,70.0,"Crossings Republik, Ghaziabad, Delhi NCR",1.898,28.625850,77.435336,4.0,3.0,5.0,Ready to Move,Resale,NaN,NaN,NaN,NaN,Flat,\n \n \n...,3688.092729
7736,7736,65.0,"Raj Nagar Extension, Ghaziabad, Raj Nagar Exte...",1.400,28.701622,77.430153,3.0,3.0,2.0,Ready to Move,Resale,1.0,NaN,3.0,vvip mall,Flat,\n \n \n...,4642.857143
7737,7737,65.0,"sandal apartment, Shalimar Garden Extension 1,...",1.750,28.693590,77.344376,3.0,2.0,3.0,Ready to Move,New Property,NaN,NaN,NaN,NaN,Flat,\n,3714.285714

In [187]:
df['Bedrooms'] = df['Bedrooms'].replace(np.nan, 0)

df['Bathrooms']=df['Bathrooms'].replace(np.nan,0)

df['Balcony']=df['Balcony'].replace(np.nan,0)

In [188]:
df

,Unnamed: 0,price,Address,area,latitude,longitude,Bedrooms,Bathrooms,Balcony,Status,neworold,parking,Furnished_status,Lift,Landmarks,type_of_building,desc,Price_sqft
0,0,56.0,"Noida Extension, Noida, Delhi NCR",1.350,28.608850,77.460560,3.0,3.0,0.0,Under Construction,New Property,NaN,NaN,2.0,NaN,Flat,\n\n\n Welcome ...,4148.148148
1,1,88.0,"Sector 79, Gurgaon, Delhi NCR",1.490,28.374236,76.952416,3.0,3.0,0.0,Ready to Move,New Property,NaN,Semi-Furnished,2.0,NaN,Flat,\n\n\n Mapsko M...,5906.040268
2,2,165.0,"Vaishali, Ghaziabad, Delhi NCR",2.385,28.645769,77.385110,4.0,5.0,0.0,Ready to Move,New Property,1.0,Unfurnished,NaN,NaN,Flat,\n\n\n This pro...,6918.238994
3,3,38.1,"Link Road, F Block, Sector 50, Noida, Uttar Pr...",1.050,28.566914,77.436434,2.0,2.0,3.0,NaN,New Property,1.0,Unfurnished,2.0,near Gaur Mulberry Mansion,Flat,\n\n\n AIG Roya...,3628.571429
4,4,62.0,"Jaypee Pavilion Court Sector 128, Noida, Secto...",1.350,28.520732,77.356491,2.0,2.0,3.0,Ready to Move,Resale,1.0,NaN,3.0,NaN,Flat,\n\n\n The prop...,4592.592593
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7733,7733,79.0,"Indirapuram, Ghaziabad, Delhi NCR",1.095,28.635272,77.370395,2.0,2.0,0.0,Ready to Move,Resale,NaN,NaN,NaN,NaN,Flat,\n \n \n...,7214.611872
7734,7734,45.1,"Greater Noida, Sector 2, Greater Noida, Delhi NCR",1.060,28.581431,77.452819,2.0,2.0,3.0,NaN,Resale,NaN,Semi-Furnished,NaN,ek murti chowk,Flat,\n \n \n...,4254.716981
7735,7735,70.0,"Crossings Republik, Ghaziabad, Delhi NCR",1.898,28.625850,77.435336,4.0,3.0,5.0,Ready to Move,Resale,NaN,NaN,NaN,NaN,Flat,\n \n \n...,3688.092729
7736,7736,65.0,"Raj Nagar Extension, Ghaziabad, Raj Nagar Exte...",1.400,28.701622,77.430153,3.0,3.0,2.0,Ready to Move,Resale,1.0,NaN,3.0,vvip mall,Flat,\n \n \n...,4642.857143
7737,7737,65.0,"sandal apartment, Shalimar Garden Extension 1,...",1.750,28.693590,77.344376,3.0,2.0,3.0,Ready to Move,New Property,NaN,NaN,NaN,NaN,Flat,\n,3714.285714

In [205]:
x=np.array([df['area'],df['Bedrooms']])
y=np.array(df['price'])


x.shape,y.shape

((2, 7738), (7738,))

In [206]:
x=x.T
x,y,x.shape

(array([[1.35 , 3.   ],
        [1.49 , 3.   ],
        [2.385, 4.   ],
        ...,
        [1.898, 4.   ],
        [1.4  , 3.   ],
        [1.75 , 3.   ]]),
 array([ 56.,  88., 165., ...,  70.,  65.,  65.]),
 (7738, 2))

In [209]:
#x=np.array([[2.104, 5, 1, 45], [1.416, 3, 2, 40], [0.852, 2, 1, 35]])
#y = np.array([460, 232, 178])

b=785.1811367994083
w = np.random.randn(2)
#print(w,b)
def cost(x,y,w,b):
    '''
    note: x is the input matrix (n,m)      n training examples with m features
          y is the price matrix, (n,)      
          w is the weight matrix (m,)      weight for each feature
          b is a scalar
          '''
    
    y_hat=np.dot(x,w)+b
    #y_hat=np.sum(y_hat,1)
    print(y_hat)
    loss=(y_hat-y)**2
    loss=np.sum(loss)
    cost=loss/(2*len(y))
    #print(y_hat,y)
    return cost

    print(y_hat.shape)

cost(x,y,w,b)

[788.53240043 788.62234604 790.02533245 ... 789.71245023 788.56452386
 788.78938788]

251147.8325731363

In [211]:
def gradient(x,y,w,b):
    '''dj_dw is an array of m elements with dj_dw[i] 0<=i<m
       dj_db is also an array of m '''
    f=np.dot(x,w)+b
    k=len(y)
    J=f-y
    m=x.shape[1]
    #print(f)
    dj_dw=np.zeros(m)
    '''
    now, to compute gradient:
    
    J=sum((fi-y)**2)/2m, where f=w1x_i1+w2x_i2+w3x_i3 +b 
    therefore,
     dj_dw1= (1/m)*sum(x1*(fi-y)) '''
    dj_db=np.sum(J)/k
    #print(dj_db)
    #print(x[:,0])
    #for i in range(m):
    dj_dw= np.dot((f-y),x)

    dj_dw/=k
   # print(dj_dw)
    return dj_dw,dj_db


gradient(x,y,w,b)

(array([ 950.47743038, 1872.07955653]), 705.1226770303952)

In [214]:
def gradient_descent(x,y,w,b,alpha):
    wt=w
    bt=b

    for i in range(10000):
        dj_dw,dj_db=gradient(x,y,wt,bt)
        wt= wt - alpha*dj_dw

        bt= bt - alpha*dj_db
        
        if i%1000==0:
            print(f"cost: {cost(x,y,wt,bt)}")
    
    return wt,bt

In [215]:
w=np.random.randn(2)/100
b=0
w,b=gradient_descent(x,y,w,b,0.01)

[10.94192698 11.16745975 15.25434519 ... 14.46981335 11.02247439
 11.58630631]
cost: 5101.03583378748
[ 80.86511588  91.53906747 161.98993244 ... 124.85982941  84.67724145
 111.36212042]
cost: 739.8800063767826
[ 79.47231623  90.9391814  166.44644033 ... 126.55813077  83.56762522
 112.23478815]
cost: 725.9792648625223
[ 79.44068865  90.9412164  167.62344894 ... 127.61804169  83.54801999
 112.29933937]
cost: 724.7510734696543
[ 79.48580798  90.96912847 168.06167341 ... 128.11612283  83.58699387
 112.29529511]
cost: 724.5284358747336
[ 79.51165528  90.98415296 168.24638562 ... 128.33848299  83.60897588
 112.29022007]
cost: 724.4854978885895
[ 79.52363609  90.99104183 168.32682912 ... 128.43663916  83.61913814
 112.28765249]
cost: 724.4771884229895
[ 79.52896899  90.99410095 168.36213715 ... 128.4798567   83.62365897
 112.28648887]
cost: 724.4755800601936
[ 79.5313215   90.99544969 168.3776626  ... 128.49887383  83.625653
 112.28597347]
cost: 724.4752687458137
[ 79.53235714  90.99604337 168.38449222 ... 128.50724084  83.6265308
 112.28574637]
cost: 724.4752084878335

In [216]:
w,b

(array([81.88208484,  4.10672457]), -43.32817569187114)

In [200]:
x_in=[2,4,1,35]
y_out=np.dot(x_in,w)+b

y_out

64.45303722338497

In [218]:
x_in=[1.49 , 3.   ]

y_out=np.dot(x_in,w)+b
y_out

90.99630442432218